# Generated by Django 4.2.7 on 2025-12-17 04:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('BID_PAYMENT', 'Bid Payment'), ('SUBSCRIPTION', 'Subscription Fee'), ('COMMISSION', 'Platform Commission'), ('WITHDRAWAL', 'Withdrawal'), ('REFUND', 'Refund'), ('REFERRAL_BONUS', 'Referral Bonus'), ('PREMIUM_UPGRADE', 'Premium Upgrade')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sender_name', models.CharField(help_text='Name of person who sent the payment', max_length=200)),
                ('ecocash_reference', models.CharField(help_text='EcoCash transaction reference (TXN ID)', max_length=50)),
                ('sender_phone', models.CharField(blank=True, help_text='Phone number that sent payment', max_length=15)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes (especially if rejected)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_payment', to='payments.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_payments', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Manual Payment',
                'verbose_name_plural': 'Manual Payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
