# Generated by Django 4.2.7 on 2025-11-15 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_alter_conversation_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='conversation',
            name='unique_bid_conversation',
        ),
        migrations.RemoveConstraint(
            model_name='conversation',
            name='unique_offer_conversation',
        ),
    ]
