# Generated by Django 4.2.7 on 2025-09-23 04:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bids', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='bids.bid')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bid View',
                'verbose_name_plural': 'Bid Views',
                'unique_together': {('bid', 'viewer')},
            },
        ),
    ]
