# Generated by Django 4.2.7 on 2025-10-14 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bids', '0002_bidview'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SELECTED', 'Selected'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], default='PENDING', max_length=20)),
                ('message', models.TextField(blank=True, max_length=500)),
                ('accepted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_acceptances', to=settings.AUTH_USER_MODEL)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acceptances', to='bids.bid')),
            ],
            options={
                'verbose_name': 'Bid Acceptance',
                'verbose_name_plural': 'Bid Acceptances',
                'ordering': ['-accepted_at'],
                'unique_together': {('bid', 'accepted_by')},
            },
        ),
    ]
