# Generated by Django 4.2.7 on 2025-12-05 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0003_bidacceptance'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bid_type',
            field=models.CharField(choices=[('MONEY', 'Money'), ('PERKS', 'Perks')], default='MONEY', max_length=20),
        ),
        migrations.AddField(
            model_name='bid',
            name='total_perk_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Sum of estimated values for all perks', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='bid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='BidPerk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('CONCERT_TICKETS', '🎵 Concert Tickets'), ('ALCOHOL', '🍷 Alcohol/Beverages'), ('DINING', '🍽️ Lunch/Dinner'), ('FUEL', '⛽ Fuel Coupons'), ('TRANSPORT', '🚗 Transportation'), ('SHOPPING', '🛍️ Shopping Vouchers'), ('ENTERTAINMENT', '🎬 Entertainment'), ('OTHER', '✨ Other')], max_length=50)),
                ('description', models.TextField(help_text="e.g., '2 VIP tickets to Taylor Swift concert'", max_length=200)),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, help_text='Optional estimated value in USD for sorting/filtering', max_digits=10, null=True)),
                ('quantity', models.IntegerField(default=1, help_text='Number of items (e.g., 2 tickets)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perks', to='bids.bid')),
            ],
            options={
                'verbose_name': 'Bid Perk',
                'verbose_name_plural': 'Bid Perks',
                'ordering': ['category', 'created_at'],
            },
        ),
    ]
