# Generated by Django 4.2.7 on 2025-09-11 03:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_bid_updates', models.BooleanField(default=True)),
                ('email_messages', models.BooleanField(default=True)),
                ('email_payments', models.BooleanField(default=True)),
                ('email_promotions', models.BooleanField(default=True)),
                ('email_system', models.BooleanField(default=True)),
                ('push_bid_updates', models.BooleanField(default=True)),
                ('push_messages', models.BooleanField(default=True)),
                ('push_payments', models.BooleanField(default=True)),
                ('push_promotions', models.BooleanField(default=False)),
                ('push_system', models.BooleanField(default=True)),
                ('sms_payments', models.BooleanField(default=False)),
                ('sms_urgent', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('BID_ACCEPTED', 'Bid Accepted'), ('BID_CANCELLED', 'Bid Cancelled'), ('NEW_MESSAGE', 'New Message'), ('PAYMENT_RECEIVED', 'Payment Received'), ('PAYMENT_SENT', 'Payment Sent'), ('WITHDRAWAL_PROCESSED', 'Withdrawal Processed'), ('REFERRAL_BONUS', 'Referral Bonus'), ('PREMIUM_EXPIRING', 'Premium Expiring'), ('EVENT_REMINDER', 'Event Reminder'), ('SYSTEM_ANNOUNCEMENT', 'System Announcement')], max_length=30)),
                ('related_object_type', models.CharField(blank=True, max_length=50)),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
