# Generated by Django 4.2.7 on 2025-11-16 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_webpushsubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('BID_ACCEPTED', 'Bid Accepted'), ('BID_CANCELLED', 'Bid Cancelled'), ('NEW_MESSAGE', 'New Message'), ('OFFER_BID', 'Offer Bid'), ('OFFER_ACCEPTED', 'Offer Accepted'), ('PAYMENT_RECEIVED', 'Payment Received'), ('PAYMENT_SENT', 'Payment Sent'), ('WITHDRAWAL_PROCESSED', 'Withdrawal Processed'), ('REFERRAL_BONUS', 'Referral Bonus'), ('PREMIUM_EXPIRING', 'Premium Expiring'), ('EVENT_REMINDER', 'Event Reminder'), ('SYSTEM_ANNOUNCEMENT', 'System Announcement')], max_length=30),
        ),
    ]
